version: "3.8"

services:
  db:
    image: postgres:15
    container_name: intuitivecare_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: IntuitiveCare
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/data:ro  # Monta CSVs dentro do container

volumes:
  pgdata:
